### ISSUE TITLE
Queries with custom name attributes

### ISSUE THREAD

**Issue by Fudoshiki** [zookzook/elixir-mongodb-driver#157]
```elixir
defmodule MyApp.Session do
  @moduledoc false
  use Mongo.Collection

  alias BSON.Binary

  collection :s do
    attribute :uuid, Binary.t(), name: :u

    timestamps inserted_at: {:inserted_at, :i_at}, updated_at: {:updated_at, :u_at}
  end
end
```

After https://github.com/zookzook/elixir-mongodb-driver/commit/e7f2d44a01fa25cd85cb8fd1f935ba5a201fe011 can't do request

```elixir
MyApp.Repo.get_by(MyApp.Session, %{uuid: session_uuid})
```

How can I convert `%{uuid: session_uuid}` to `%{u: session_uuid}` now?

**Comment by zookzook** [comment]
Keep in mind, that the collection macro is just a very simple macro. It does not support the rewriting of queries. In this case you have to use the query for the document representation in the database:

```
MyApp.Repo.get_by(MyApp.Session, %{u: session_uuid})
```

It is too complex to rewrite, because you can create complex queries with nested documents, complex aggregations etc. I think to support such rewriting of queries and aggregation pipeline belongs to an own project.
