### ISSUE TITLE
Reconnecting to ReplicaSets

### ISSUE THREAD

**Issue by leonardo940707** [zookzook/elixir-mongodb-driver#179]
First of all, thanks for this incredible work, I've been using this driver for a while.

After upgrading my Mongo Atlas ReplicaSet from 4.2 all the way up to 6.0, I'm having some problems in the reconnection after some time has passed and all the queries return an error of:

`** (exit) exited in: GenServer.call(:mongo, {:checkout_session, :read, []}, 60000) ` or
`** (stop) exited in: GenServer.call(:mongo, {:checkout_session, :write, [write_counter: 1]}, 60000)`

This starts to happen after this errors of connection to the seeds of the ReplicaSet:

`[error] Mongo.MongoDBConnection (#PID<0.5172.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.5169.0> timed out because it queued and checked out the connection for longer than 30000ms`

`[warning] Unable to round trip time because of {:error, %Mongo.Error{code: nil, error_labels: nil, fail_command: nil, host: "cluster0-shard-00-00.XXXXX.mongodb.net:27017", message: "cluster0-shard-00-00.XXXXX.mongodb.net:27017 tcp recv: unknown POSIX error - :closed", not_writable_primary_or_recovering: nil, resumable: true, retryable_reads: nil, retryable_writes: nil}}`

After restarting the server all the connection starts to work perfectly, and after a while the errors starts to popup again.

I'm currently using version 1.0.2 of the driver and starting it as a child of the Application Supervisor, with a pool of 100 connections, using the SRV URI  to connect to the ReplicaSet.

**Comment by zookzook** [comment]
If the `Mongo.Topology.get_state(:mongo)` timed out then it seems that there is a network issue. Do you run your application locally or somewhere in the cloud?

**Comment by zookzook** [comment]
Can you stop the time between the start and the first timeout?

**Comment by leonardo940707** [comment]
The application currently have two nodes each in an instance of the OracleCloud using the syn lib to register processes between, both of them connects to the Mongo Atlas but the problem seems to occur at random times in the two nodes, sometimes it happen on the first node, at other times it happens on the second one. If I wait long enough both of them shows the same problem.

**Comment by zookzook** [comment]
Could you try it out using your local environment? It would be helpful if you are able to reproduce it. If not, then you need to check your OracleCloud environment.

**Comment by leonardo940707** [comment]
Ok, I'll try!

**Comment by zookzook** [comment]
Is there any news on this topic?

**Comment by zookzook** [comment]
Closing due to no response.

**Comment by ksmithut** [comment]
@zookzook I'm running into a similar error here, but I'm not sure how best to reproduce the issue. We've had several outages that seem to be caused by the mongo driver disconnecting from the mongo cluster and is unable to recover. The symptoms sound similar to this, but I'm unable to reproduce in a local environment to effectively reproduce the issue.

We see a log that looks like this:

```
19:44:53.571 [error] Mongo.MongoDBConnection (#PID<0.16122.6>) disconnected: ** (Mongo.Error) {{hostname}}:27017 tcp recv: unknown POSIX error - :closed
```

We receive a bunch of those all for different PIDs, then we start receiving similar issues, but instead of `:closed` it says `:timeout`:

```
19:45:20.605 [error] Mongo.MongoDBConnection (#PID<0.15637.1>) failed to connect: ** (Mongo.Error) {{hostname}}:27017 tcp connect: unknown POSIX error - :timeout
```

I've been keeping track of the srv entries for our cluster and they don't see to change at all over time, though it's definitely possible that the ip addresses underneath the hostnames for the cluster change. Looking at our mongo logs, this event seems to happen when a server in our mongo cluster is having issues and it shuts down and a new primary is elected. There's probably more going on than that (possible swapping of ips, etc). However, I tried just doing a simple replicaset and terminating a node (or restarting it) and the driver recovers fine. I can't however get it to do any `:timeout` errors. I'm thinking that our hosting provider is swapping out instances under the hood and is holding onto the request longer than the configured timeout.

**Comment by zookzook** [comment]
It seems that this is a network issue. The `:closed` error is returned when the server closed the connection. And the `:timeout` is the result when connecting to the server. And if you have a cluster with virtual servers it could be the side effects of some issues in the network layer (routing issues for example). In this case, you need to log in to your server and try to connect to the DB directly to check the network connection.

**Comment by ksmithut** [comment]
It's odd, though, because we have other drivers in other languages that seem to handle this reconnection just fine (we also see connections closing but they reconnect pretty quickly, usually without us evening knowing that a reelection event happened. We can keep this issue closed and once I can gather more helpful details I'll open up another issue. Thank you :)

**Comment by zookzook** [comment]
Sounds good! Thank you.

**Comment by justmark** [comment]
Hi,

I seem to be having a similar issue here.  I have two Atlas clusters.  One works fine, but the other runs into issues with two of the replica nodes.

```

**Comment by zookzook** [comment]
Sorry, this is impossible without more information about your system.

try this https://github.com/zookzook/elixir-mongodb-driver/issues/179#issuecomment-1455911953 and post the output here

**Comment by zookzook** [comment]
If one cluster is fine and the other has an issue, maybe the configuration is not correct.

**Comment by zookzook** [comment]
If I try to connect to a MongoDB behind a firewall, I can see the timeout error:

```
unknown POSIX error: timeout - :timeout
```

**Comment by justmark** [comment]
We're on OTP/22.  I'm making some changes to that Cluster - it is configured differently than the other cluster is, so perhaps there is something with the configuration that is causing an issue.  Will update shortly.

**Comment by justmark** [comment]
The cluster that had the Posix errors above was split across 3 GCP regions.  My other cluster was in 1 region.  I just changed the configuration for the cluster so that all nodes are in the same region, and all my Posix errors are gone.  Still getting the odd :timeout - more soon.

**Comment by zookzook** [comment]
Maybe you need to check the firewall rules in this case. And check the replica-set as well.

**Comment by dmozgovoi** [comment]
I faced the same error message on the local setup with Docker. My setup is a non-sharded database with a single collection. I use this driver to monitor changes using ChangeStream.
When I restart Mongo container, Elixir prints the same error message and then reconnects. However, sometimes it re-creates the ChangeStream sometimes it's not.
I suspect it might occur when a whole connection pool is replaced [here](https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo/topology.ex#L248).

What the intended behaviour in this case?
