### ISSUE TITLE
How to set field to `nil`/`NULL`

### ISSUE THREAD

**Issue by aej** [zookzook/elixir-mongodb-driver#183]
I've been trying to use `Repo.update!/1` to set a field value to NULL (eg `Repo.update!(%{document | field: nil})`)

I can see in the source code that the nil values are stripped out before the update is applied (https://github.com/zookzook/elixir-mongodb-driver/blob/master/lib/mongo/collection.ex#L1003) - what is the suggested way to explicitly set `nil`/`NULL`?

**Comment by zookzook** [comment]
The functions Repo module is very limited. They don't extract differences or provide smart updates expression. Because MongoDB supports a lot of update possibilities you need to specify what you want to update. The `Repo.update!` replaces all values. I cannot recommend using the `update` function. The implementation does:

```
Mongo.update_one!(@topology, collection, %{_id: id}, %{"$set" => module.dump(doc)}, opts)
```

And currently, the `dump` function removes all nil values.

Better:

```
Mongo.update_one(topology, "documents", %{_id: ...}, %{"$set": %{field: nil}})
```

Maybe we want to remove the field instead of using nil values:

```
Mongo.update_one(topology, "documents", %{_id: ...}, %{"$unset": %{field: 1}})
```

**Comment by aej** [comment]
Great thanks - I've got it working using `Mongo.update_one` as you suggest (rather than `Repo.update`). That solves my immediate problem.
