### ISSUE TITLE
Compatible with Ecto?

### ISSUE THREAD

**Issue by scottmessinger** [zookzook/elixir-mongodb-driver#49]
Hi! Is this library compatible with Ecto as the library this was forked from? If not, would love to see that feature!

**Comment by zookzook** [comment]
Sorry, it is not compatible. I think, it does not make sense, because there are two different concepts. Ecto is built for rational databases while MongoDB is document based. So, adding an additional layer on the driver which is not compatible due to the different concepts will have more disadvantages than advantages. 

I think, it is the best to use the driver directly without using a wrapper like Ecto. If you want to use `defstruct` instead of simple maps you can convert directly manually. Using this approach you don't need to think about the syntax of the DSL to build queries, so the DSL query is translated back to the correct MongoDB query. Since the MongoDB-API uses JSON/BJSON to express queries and updates, the danger of `sql-injection` is not very high, because you need to build maps and keyword lists. Strings are not used to build query and update expressions. So, the DSL query language makes no sense at all in case of MongoDB.

**Comment by scottmessinger** [comment]
Thanks for the response! I think I actually framed my question wrong -- it was more accurate to ask if they're an ecto adapter for this driver a la https://github.com/ankhers/mongodb_ecto The driver this was forked from doesn't interface with ecto -- the adapter does the integration.

As for using Mongo with Ecto, we've been using it for 3 years and really love the combination. We have reasonably complex documents in Mongo and haven't encountered anything that Ecto can't model.

We lean on Ecto for fetching data. We drop down to the mongo driver for doing atomic updates ($set and friends) -- all places where we want to very precisely use what Mongo offers.

So, for us, we don't see an either or with Mongo or Ecto -- we see them very much as complimentary and really appreciate the the other Mongo driver lets us use it stand alone or integrate with Ecto. It lets us have the best of both worlds.

I haven't looked into how the mongodb_ecto adapter was written, but if this library added instead of changed the API from the other driver, I imagine it either works now or would be in a good place to add compatibility. On a related note, how stable do you feel your work is now? Is the api something that could be relied on as is? Or, do you have plans to change it in small or large ways?

**Comment by zookzook** [comment]
>I haven't looked into how the mongodb_ecto adapter was written, but if this library added instead of changed the API from the other driver, I imagine it either works now or would be in a good place to add compatibility.

It is possible to the this driver for the `mongodb_ecto` adapter, but I think it needs some work. An interesting part is the transaction API, for example.

> On a related note, how stable do you feel your work is now? Is the api something that could be relied on as is? Or, do you have plans to change it in small or large ways?

The API is stable so far. I try to integrate the test files from the specification and adding stuff like 'retryable' reads and writes. But before that I need to extend the event broadcasting module, so the test cases can fetch events in order to receive curtain events.

My plans are
* add more test from the driver specs
* add missing features like retryable writes, errorLabels, retryable commits
